import { motion } from "framer-motion";
import { ArrowRight, Sparkles } from "lucide-react";
import { Link } from "react-router-dom";

const SummarizerHero = () => {
  return (
    <section className="relative overflow-hidden py-28 lg:py-36">
      <div className="absolute left-1/2 top-0 h-96 w-96 -translate-x-1/2 rounded-full bg-cyan-500/10 blur-[140px]" />

      <div className="relative mx-auto w-[92%] max-w-7xl">

        <motion.div
          initial={{ opacity: 0, y: 30 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: .6 }}
          className="mx-auto max-w-4xl text-center"
        >

          <span className="inline-flex items-center gap-2 rounded-full border border-cyan-500/20 bg-cyan-500/10 px-4 py-2 text-sm font-medium text-cyan-400">
            <Sparkles className="h-4 w-4" />
            AI Research Summarizer
          </span>

          <h1 className="mt-8 text-5xl font-bold leading-tight text-foreground lg:text-7xl">
            Understand research papers
            <span className="block text-cyan-400">
              in minutes.
            </span>
          </h1>

          <p className="mx-auto mt-8 max-w-3xl text-lg leading-8 text-muted">
            Upload any research paper and receive accurate summaries,
            key findings, methodologies, limitations, research gaps,
            and citations generated by AI.
          </p>

          <div className="mt-12 flex flex-col items-center justify-center gap-5 sm:flex-row">

            <Link
              to="/register"
              className="rounded-2xl bg-cyan-500 px-7 py-4 font-semibold text-slate-950 transition hover:scale-105"
            >
              Try AI Summarizer
            </Link>

            <Link
              to="/workspace"
              className="inline-flex items-center gap-2 rounded-2xl border border-border px-7 py-4 transition hover:border-cyan-400 hover:text-cyan-400"
            >
              Explore Workspace

              <ArrowRight className="h-5 w-5" />
            </Link>

          </div>

          <div className="mt-20 flex flex-wrap items-center justify-center gap-10">

            <div>
              <h3 className="text-4xl font-bold text-cyan-400">
                30 sec
              </h3>

              <p className="mt-2 text-muted">
                Average summary time
              </p>
            </div>

            <div>
              <h3 className="text-4xl font-bold text-cyan-400">
                98%
              </h3>

              <p className="mt-2 text-muted">
                Summary accuracy
              </p>
            </div>

            <div>
              <h3 className="text-4xl font-bold text-cyan-400">
                100+
              </h3>

              <p className="mt-2 text-muted">
                Supported document formats
              </p>
            </div>

          </div>

        </motion.div>

      </div>
    </section>
  );
};

export default SummarizerHero;